app:
    resource: "@AppBundle/Controller/"
    type:     annotation

file_list:
    path:      /file/list
    defaults:  { _controller: AppBundle:File:list }

file_add:
    path:      /file/add
    defaults:  { _controller: AppBundle:File:add }

login:
    path:      /auth
    defaults:  { _controller: AppBundle:User:login }

default:
    path:      /
    defaults:  { _controller: AppBundle:File:list }
