app:
    resource: "@AppBundle/Controller/"
    type:     annotation

file_list:
    path:      /files.html
    defaults:  { _controller: AppBundle:File:list }

file_add:
    path:      /upload.html
    defaults:  { _controller: AppBundle:File:add }

login:
    path:      /auth.html
    defaults:  { _controller: AppBundle:User:login }

logout:
    path:      /exit.html
    defaults:  { _controller: AppBundle:User:logout }

register:
    path:      /register.html
    defaults:  { _controller: AppBundle:User:register }

default:
    path:      /
    defaults:  { _controller: AppBundle:File:list }
