<?php

namespace AppBundle\Entity;

/**
 * FileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FileRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAll()
    {
        return $this->findBy(array(), array('id' => 'DESC'));
    }
}
